### ISSUE TITLE
depend on libxml2 which not support windows os

### ISSUE THREAD

**Issue by loachfish** [wtnb75/davgo#1]
```
# pkg-config --cflags  -- libxml-2.0 libxml-2.0
pkg-config: exec: "pkg-config": executable file not found in %PATH%
# pkg-config --cflags  -- libxml-2.0
pkg-config: exec: "pkg-config": executable file not found in %PATH%
```

**Comment by wtnb75** [comment]
hi @loachfish, Thank you for your report.
gokogiri which is used by this davgo depends on libxml2.

this software is in very early stage, and development has been stopped since 4 years ago... 😞

**Comment by loachfish** [comment]
have found a webdav library:
https://github.com/remogatto/cloud.git

perfect adapter the cloud operation.
